---
title: "Working"
author: "Shubham Khalkho"
date: "2024-06-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = TRUE, eval = TRUE}
library(ggplot2)
library(dplyr)
df = 1
t = (1:400)/100
y1 = dchisq(t, df = 1)
plot(t, y1, type="l",lwd=2,col="black",ylim=c(0,1.5),ylab="density")
## now, adding new plots
y2 = dchisq(t,df=2)
y3 = dchisq(t,df=3)
y4 = dchisq(t,df=4)
lines(t, y2, lwd=2,col="red")
lines(t, y3, lwd=2,col="blue")
lines(t, y4, lwd=2,col="green")

## and we add a legend, too

legend(x=3,y=1,legend=c("df=1", "df=2", "df=3", "df=4"),
       col=c("black", "red", "blue", "green"), lty="solid", cex=0.8)

abline(a=0.5, b=2, lwd=4, lty='dashed')
```

```{r}
data(iris)
x = iris$Petal.Length
y = iris$Sepal.Length


plot(x,y,pch=16, xlab='Petal Length',
                 ylab='Sepal Length',
                 main='Iris Sepal Length VS Petal Length',
                  col=iris$Species)

#Legend
legend("topleft",legend=unique(iris$Species),
       fill=unique(iris$Species),bty='n')
```

```{r}

```
